name: DAST - ZAP Baseline
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install & run app (Flask)
        env:
          FLASK_APP: app/app.py
        run: |
          pip install -r requirements.txt
          nohup python app/app.py >/dev/null 2>&1 &
          for i in {1..60}; do
            if curl -sSf http://localhost:8000 >/dev/null; then echo "App up"; break; fi
            sleep 2
          done
      - name: ZAP Baseline
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8000'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Relatório de Vulnerabilidades DAST'
          fail_action: true
          rules_file_name: 'zap-rules.tsv'